#spring:
#  application:
#    name: gateway-service
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: auth-service
#              uri: http://localhost:8081
#              predicates:
#                - Path=/auth/**
#            - id: user-service
#              uri: http://localhost:8082
#              predicates:
#                - Path=/user/**
#            - id: task-service
#              uri: http://localhost:8083
#              predicates:
#                - Path=/task/**
#eureka:
#  instance:
#    hostname: localhost   # ðŸ‘ˆ force it to register as localhost
#    prefer-ip-address: true

server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          #http://localhost:8081
          #lb://AUTH-SERVER            #8081
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://localhost:8082
          #http://localhost:8082
          #lb://USERPROFILE-SERVICE    #8082
          predicates:
            - Path=/users/**
          filters:
            - name: RemoveRequestHeader
              args:
                name: Cookie
            - name: AddRequestHeader
              args:
                name: X-Forwarded-Host
                value: gateway
        - id: task-service
          uri: http://localhost:8083
          #http://localhost:8083
          #lb://TASK-SERVICE   #8083
          predicates:
            - Path=/tasks/**
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: TRACE